### ISSUE TITLE
Dynamically create React Native navigation from a JSON

### ISSUE THREAD

**Issue by raphkhan** [moh3n9595/react-native-dynamic-render#2]
Essentially, my whole React-Native components are dynamically rendered from a JSON (hosted on Firebase) thanks to react-native-dynamic-render.

My problem is I need the React-Navigation to be dynamically created using that same idea.... For instance, if I delete the page from the pages table, the tab should not be there; if I add one, it should add it on the next app load, etc.

Any ideas on how to do that? Thanks :)

**Comment by moh3n9595** [comment]
Hey @raphkhan, since the latest React-Navigation version use components to render screens ([sample](https://reactnavigation.org/docs/hello-react-navigation)), you should not have any problem to use them in your JSON. But I try to implement a better demo-example later to see how you can do that.

**Comment by moh3n9595** [comment]
Check the latest version ([1.1.3](https://github.com/moh3n9595/react-native-dynamic-render/releases/tag/v1.1.3)). I added a new feature to simplify your idea. For more information,  see the [example](https://snack.expo.io/@moh3n95/react-navigation-dynamic-render).

**Comment by raphkhan** [comment]
@moh3n9595 Thanks a lot!
