### ISSUE TITLE
Question about dynamic import statements

### ISSUE THREAD

**Issue by Menganitou** [moh3n9595/react-native-dynamic-render#3]
Hi there @moh3n9595 ! Do you think its possible to make dynamic "import" statements? Or some workarrounds.

I find no way to make it work. Its seems that you must write all the imports before. 

Thanks!

**Comment by moh3n9595** [comment]
Hey @Menganitou,

Yes, you can do that. But it's irrelevant to `react-native-dynamic-render`; Although you can create a nice demo-example to show the usage of dynamic imports besides of `react-native-dynamic-render`. ([link](https://reactjs.org/docs/code-splitting.html))
